version: "3.8"
services:
  backend: 
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - backend/.env

  frontend:
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    
  minio:
    container_name: cs_curriculum_minio_str
    image: minio/minio
    env_file:
      - .env.example
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  db:
    container_name: cs_curriculum_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=cs_curriculum
    ports:
      - "3306:3306"
    volumes:
      - csc_db_data:/var/lib/mysql

  phpmyadmin:
    container_name: cs_curriculum_phpmyadmin_db
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  csc_db_data:
  minio_data: