name: CI/CD

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  test-and-build-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
 
      - name: Copy environment
        run: cp .env.example ./backend/.env

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./Docker-compose.yml"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run tests
        working-directory: ./backend
        run: |
          if [ -f pytest.ini ]; then
            pytest
          else
            echo "ไม่มี UAT/Unit Testing"
          fi
  
  # build-and-release-main:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Build Docker image
  #     run: |
  #       docker build -t backend backend
  #       docker build -t frontend frontend

  #   - name: Log in to Docker Hub 
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
    
    